-- Progress Claw Machine: Phase A/A.1 machine status schema
-- Run in the Supabase SQL Editor. The unique machine_name constraint prevents
-- diagnostic reruns from creating uncontrolled duplicate rows.

create table if not exists public.machine_status (
    id bigint generated by default as identity primary key,
    machine_name text not null unique,
    status text not null,
    x_position double precision not null default 0,
    y_position double precision not null default 0,
    claw_power integer not null default 0 check (claw_power between 0 and 100),
    online boolean not null default false,
    updated_at timestamptz not null default now()
);

alter table public.machine_status enable row level security;

-- Create policies appropriate to your deployment key. Do not add a public
-- anonymous write policy unless that access model has been explicitly reviewed.
